<a href="https://colab.research.google.com/github/farruxisomiddinov326-cell/collab_uchun/blob/main/homework3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
from pandas import Series

In [ ]:
obj = Series([4,7,6,-6.5])

In [ ]:
print(obj)

0    4.0
1    7.0
2    6.0
3   -6.5
dtype: float64

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj.values

array([ 4. ,  7. ,  6. , -6.5])

In [ ]:
obj[0]

np.float64(4.0)

In [ ]:
np.float64(4.0)

np.float64(4.0)

In [ ]:
obj2 = Series([1,2,3],index=['a','b','c'])
obj2

a    1
b    2
c    3
dtype: int64

In [ ]:
dtype:np.int64

In [ ]:
s = Series([85,90,78], index=["ali", "vali", "sami"])
s

ali     85
vali    90
sami    78
dtype: int64

In [ ]:
obj2[obj2 < 3]

a    1
b    2
dtype: int64

In [ ]:
obj * 2

0     8.0
1    14.0
2    12.0
3   -13.0
dtype: float64

In [ ]:
from google.colab import files
upload = files.upload()

Saving Talabalar_.csv to Talabalar_.csv

In [ ]:
df = pd.read_csv('Talabalar_.csv')
df.head()

   ID    Name  Gender Age Score Enrollment Date          Phone
0   1     NaN    male  20    64      09.02.2026   998902458591
1   2  Lola      MALE  17    85        26.02.13            NaN
2   3  Sami    female  22    67      2026/02/10   998906647119
3   4  Anna      male  29    52        26.03.19  99890 3094235
4   5   Zara     MALE  20    95      05.02.2026   998904823498

In [ ]:
df.isnull().sum()

ID                   0
Name                25
Gender               0
Age                 28
Score                6
Enrollment Date      0
Phone              180
dtype: int64

In [ ]:
df.shape

(500, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               500 non-null    int64
 1   Name             475 non-null    object
 2   Gender           500 non-null    object
 3   Age              472 non-null    object
 4   Score            494 non-null    object
 5   Enrollment Date  500 non-null    object
 6   Phone            320 non-null    object
dtypes: int64(1), object(6)
memory usage: 27.5+ KB

In [ ]:
df.isnull().any()

ID                 False
Name                True
Gender             False
Age                 True
Score               True
Enrollment Date    False
Phone               True
dtype: bool

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [ ]:
df.head()

   id    name  gender age score enrollment_date          phone
0   1     NaN    male  20    64      09.02.2026   998902458591
1   2  Lola      MALE  17    85        26.02.13            NaN
2   3  Sami    female  22    67      2026/02/10   998906647119
3   4  Anna      male  29    52        26.03.19  99890 3094235
4   5   Zara     MALE  20    95      05.02.2026   998904823498

In [ ]:
df["name"] = df["name"].str.strip()
df["gender"] = df["gender"].str.strip().str.lower()

In [ ]:
df.head()

   id  name  gender age score enrollment_date          phone
0   1   NaN    male  20    64      09.02.2026   998902458591
1   2  Lola    male  17    85        26.02.13            NaN
2   3  Sami  female  22    67      2026/02/10   998906647119
3   4  Anna    male  29    52        26.03.19  99890 3094235
4   5  Zara    male  20    95      05.02.2026   998904823498

In [ ]:
df["gender"] = df["gender"].replace({
    "phone": "phone",
    "score": "score"
})

In [ ]:
df.head()

   id  name  gender age score enrollment_date          phone
0   1   NaN    male  20    64      09.02.2026   998902458591
1   2  Lola    male  17    85        26.02.13            NaN
2   3  Sami  female  22    67      2026/02/10   998906647119
3   4  Anna    male  29    52        26.03.19  99890 3094235
4   5  Zara    male  20    95      05.02.2026   998904823498

In [ ]:
df["gender"].value_counts()

gender
female    252
male      248
Name: count, dtype: int64

In [ ]:
df["age"] = pd.to_numeric(df["age"], errors="coerce")

In [ ]:
df.head()

   id  name  gender   age score enrollment_date          phone
0   1   NaN    male  20.0    64      09.02.2026   998902458591
1   2  Lola    male  17.0    85        26.02.13            NaN
2   3  Sami  female  22.0    67      2026/02/10   998906647119
3   4  Anna    male  29.0    52        26.03.19  99890 3094235
4   5  Zara    male  20.0    95      05.02.2026   998904823498

In [ ]:
df["enrollment_date"] = pd.to_datetime(df["enrollment_date"], errors="coerce")

In [ ]:
df.head()

   id  name  gender   age score enrollment_date          phone
0   1   NaN    male  20.0    64      2026-09-02   998902458591
1   2  Lola    male  17.0    85             NaT            NaN
2   3  Sami  female  22.0    67             NaT   998906647119
3   4  Anna    male  29.0    52             NaT  99890 3094235
4   5  Zara    male  20.0    95      2026-05-02   998904823498

In [ ]:
df["phone"] = df["phone"].astype(str).str.replace(" ", "")

In [ ]:
df.head()

   id  name  gender   age score enrollment_date         phone
0   1   NaN    male  20.0    64      2026-09-02  998902458591
1   2  Lola    male  17.0    85             NaT           nan
2   3  Sami  female  22.0    67             NaT  998906647119
3   4  Anna    male  29.0    52             NaT  998903094235
4   5  Zara    male  20.0    95      2026-05-02  998904823498